name: "Hello Actions"
description: "Greet someone"
author: "Ravi Tellakula"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Ravi"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
